- hosts: localhost
  tasks:
    - name: install python-routes pack
      package:
         name: python-routes
         state: present
    - name: Create file /tmp/xxx.txt
      file: 
          path: /tmp/xxx.txt
          state: touch